version: "3.7"
services:
  front:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    networks:
      - frontBack
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"

  back:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
    networks:
      - mongo
      - frontBack
    environment:
      - MONGO_URI=mongodb://mongodb:27017/person_db
    depends_on:
      - mongodb
    volumes:
      - "./backend:/app"
      - "/app/node_modules"

  mongodb:
    image: mongo:latest
    networks:
      - mongo
    command: mongod --noauth
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:

networks:
  mongo:
    name: mongo
  frontBack:
    name: frontBack