name: Node.js CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run docker-compose.test.yaml
      run: docker-compose -f docker-compose.test.yaml up --exit-code-from back-test
 
